[package]
name = "token-stream-stress"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
proc-macro = true

[[bin]]
name = "token-stream-stress"
path = "src/main.rs"

[workspace]