[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "collector"
version = "0.1.0"
edition = '2018'

[dependencies]
clap = "2.25"
env_logger = "0.7"
anyhow = "1"
thiserror = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
libc = "0.2"
chrono = "0.4"
cargo_metadata = "0.9"
lazy_static = "1"
semver = "0.9"
reqwest = "0.9"
xz2 = "0.1.3"
tar = "0.4"
crossbeam-channel = "0.3.8"
bincode = "1"
snap = "0.2.5"
hashbrown = "0.6.3"

[dependencies.rustup]
git = "https://github.com/rust-lang-nursery/rustup.rs.git"
optional = false

[[bin]]
name = "collector"
path = "src/bin/rustc-perf-collector/main.rs"

[[bin]]
name = "rustc-fake"
path = "src/bin/rustc-fake.rs"
